-- =====================================================
-- Campos de Visão Geral da campanha
-- Executar no SQL Editor do Supabase
-- =====================================================

-- Público recomendado e mecânica na tabela campanhas
alter table public.campanhas
    add column if not exists publico_recomendado text;

alter table public.campanhas
    add column if not exists mecanica jsonb default '[]'::jsonb;

alter table public.campanhas
    add column if not exists resumo text;

alter table public.campanhas
    add column if not exists texto_header text;

-- Garante tabela de ângulos (caso ainda não exista)
create table if not exists public.angulos_divulgacao (
    id bigint generated by default as identity primary key,
    campanha_id bigint not null references public.campanhas(id) on delete cascade,
    titulo text not null,
    descricao text,
    ordem integer default 1,
    created_at timestamptz default now()
);

alter table public.angulos_divulgacao
    add column if not exists titulo text;

alter table public.angulos_divulgacao
    add column if not exists descricao text;

alter table public.angulos_divulgacao
    add column if not exists ordem integer default 1;

create index if not exists angulos_divulgacao_campanha_id_idx
    on public.angulos_divulgacao (campanha_id);

-- Leitura pública (site)
alter table public.angulos_divulgacao enable row level security;

drop policy if exists "angulos_divulgacao_select_public" on public.angulos_divulgacao;
create policy "angulos_divulgacao_select_public"
    on public.angulos_divulgacao
    for select
    to anon, authenticated
    using (true);
